import { NgModule } from '@angular/core';
import { LucideAngularModule, Plus, Calendar, MapPin, ChevronLeft, Ticket, Phone, Link, Info, FileText, DollarSign, Users, Tag, Sparkles, CheckCircle, Star, Trash2, Pencil, Clock, Music, Headphones, Share2, CalendarPlus, CalendarDays, Percent, Layers, Home, ShoppingCart, Menu, User, ChevronRight, Shield, BarChart3, LineChart, UserCircle, TrendingUp, Settings, UsersRound, Lock, Bell, Loader2, CalendarX, List, Hash, Activity, AlertCircle, ExternalLink, Eye, ArrowLeft, Globe, Twitter, Facebook, Instagram, ChevronDown, Briefcase, AlertTriangle, ArrowRight } from 'lucide-angular';

@NgModule({
  imports: [
    LucideAngularModule.pick({
      Plus,
      Calendar,
      MapPin,
      ChevronLeft,
      Ticket,
      Phone,
      Info,
      Link,
      FileText,
      DollarSign,
      Users,
      Tag,
      Sparkles,
      CheckCircle,
      Star,
      Trash2,
      Pencil,
      Clock,
      Music,
      Headphones,
      Share2,
      CalendarPlus,
      CalendarDays,
      Percent,
      Layers,
      Home,
      ShoppingCart,
      Menu,
      User,
      ChevronRight,
      Shield,
      BarChart3,
      LineChart,
      UserCircle,
      TrendingUp,
      Settings,
      UsersRound,
      Lock,
      Bell,
      CalendarX,
      Loader2,
      List,
      Hash,
      Activity,
      AlertCircle,
      ExternalLink,
      Eye,
      ArrowLeft,
      Globe,
      Twitter,
      Facebook,
      Instagram,
      ChevronDown,
      Briefcase,
      AlertTriangle,
      ArrowRight
    })
  ],
  exports: [LucideAngularModule]
})
export class IconsModule {}
